version: "3.7"
services:
    # image project
    arquitetura:
        build:
            args:
                user: leo
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        expose:
            - 9000
        volumes:
            - ./:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - redis
            - queue
        networks:
            - arquitetura-network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8989:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - arquitetura-network

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - arquitetura-network

    # queue
    queue:
        build:
            args:
                user: leo
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - arquitetura-network

    # redis
    redis:
        image: redis:latest
        networks:
            - arquitetura-network

networks:
    arquitetura-network:
        driver: bridge
